CREATE TABLE `e_visas` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `visa_id` varchar(50) NOT NULL,
  `evisa_number` varchar(50) NOT NULL,
  `ref_number` varchar(50) NOT NULL,
  `issue_date` date NOT NULL,
  `expire_date` date NOT NULL,
  `place_of_issue` varchar(100) NOT NULL,
  `remarks` text DEFAULT NULL,
  `visa_fee` decimal(10,2) NOT NULL,
  `gender` enum('Male','Female','Other') NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `date_of_birth` date NOT NULL,
  `nationality` varchar(100) NOT NULL,
  `travel_document` varchar(100) NOT NULL,
  `travel_doc_no` varchar(50) NOT NULL,
  `travel_doc_issue` date NOT NULL,
  `travel_doc_expiry` date NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `e_visas_visa_id_unique` (`visa_id`),
  UNIQUE KEY `e_visas_evisa_number_unique` (`evisa_number`),
  KEY `e_visas_user_id_foreign` (`user_id`),
  CONSTRAINT `e_visas_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;