CREATE TABLE `visa_applications` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `visa_number` varchar(50) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `date_of_birth` date NOT NULL,
  `citizenship` varchar(100) NOT NULL,
  `passport_number` varchar(50) NOT NULL,
  `travel_document_type` varchar(50) NOT NULL,
  `passport_issue_date` date NOT NULL,
  `passport_expiry_date` date NOT NULL,
  `visa_type` varchar(100) NOT NULL,
  `visa_validity` varchar(100) NOT NULL,
  `number_of_entries` varchar(50) NOT NULL,
  `period_of_stay` int(11) NOT NULL,
  `invitation` varchar(255) DEFAULT NULL,
  `visa_issue_date` datetime NOT NULL,
  `profile_photo` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `visa_applications_user_id_foreign` (`user_id`),
  CONSTRAINT `visa_applications_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;