<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\DrivingLicenseApplication;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use TCPDF2DBarcode;
use TCPDFBarcode;

class DrivingLicenseApplicationController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $applications = DrivingLicenseApplication::latest()->get();
        return view('user.driving-licenses.index', compact('applications'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('user.driving-licenses.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate(
            $this->validationRules(),
            $this->validationMessages()
        );

        // Handle file uploads
        if ($request->hasFile('photo')) {
            $validated['photo'] = $request->file('photo')->store('licenses/photos', 'public');
        }
        if ($request->hasFile('sign')) {
            $validated['sign'] = $request->file('sign')->store('licenses/signs', 'public');
        }

        $fee = \App\Models\ServiceCharge::getCharge('driving-licenses');
        $user = auth()->user();

        if ($user->balance < $fee) {
            return back()->withErrors(['msg' => 'Insufficient balance']);
        }

        $user->balance -= $fee;
        $user->save();

        create_transaction($fee, '-', 'Created Driving License Application', $user->id);

        DrivingLicenseApplication::create($validated);

        return redirect()->route('user.driving-licenses.index')
            ->with('success', 'License application created successfully.');
    }

    /**
     * Display the specified resource.
     */


    public function show(DrivingLicenseApplication $drivingLicense)
    {
        $licenseNo = $drivingLicense->licenceNo;

        // Build the JSON payload for the PDF417 bottom barcode —
        // same structure as the reference PHP file.
        $twoDBarCodeText = json_encode([
            'LicenseNo' => $licenseNo,
            'ExpiryDate' => $drivingLicense->validityDate,
            'VechileType' => $drivingLicense->drivingClass,
            'IssueDate' => $drivingLicense->issuDate,
            'Name' => $drivingLicense->name,
        ]);

        return view('user.driving-licenses.show', [
            'photo_path' => $drivingLicense->photo,
            'sign_path' => $drivingLicense->sign,
            'name' => $drivingLicense->name,
            'dob' => $drivingLicense->dob,
            'blood_group' => $drivingLicense->bloodGroup,
            'father_or_husband' => $drivingLicense->fatherOrHusband,
            'address' => $drivingLicense->address,
            'license_no' => $licenseNo,
            'authority' => $drivingLicense->authority,
            'issue_date' => $drivingLicense->issuDate,
            'firstIssuDate' => $drivingLicense->firstIssuDate,
            'validity_date' => $drivingLicense->validityDate,
            'reference_no' => $drivingLicense->refNo,
            'driving_class' => $drivingLicense->drivingClass,

            // PDF417 bottom barcode text (JSON string, URL-encoded in the blade)
            'twoDBarCodeText' => $twoDBarCodeText,

            // NOTE: $smallBarcodeSvg and $largeBarcodeSvg are no longer needed.
            // Both barcodes are now generated by external image APIs in the view.
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(DrivingLicenseApplication $drivingLicense)
    {
        return view('user.driving-licenses.edit', ['application' => $drivingLicense]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, DrivingLicenseApplication $drivingLicense)
    {
        // For update, photo and sign are optional, so we merge custom rules
        $rules = $this->validationRules();
        $rules['photo'] = 'nullable|image|mimes:jpeg,png,jpg|max:2048';
        $rules['sign']  = 'nullable|image|mimes:jpeg,png,jpg|max:2048';

        $validated = $request->validate($rules, $this->validationMessages());

        // Handle file replacements
        if ($request->hasFile('photo')) {
            // Delete old photo
            if ($drivingLicense->photo && Storage::disk('public')->exists($drivingLicense->photo)) {
                Storage::disk('public')->delete($drivingLicense->photo);
            }
            $validated['photo'] = $request->file('photo')->store('licenses/photos', 'public');
        }
        if ($request->hasFile('sign')) {
            if ($drivingLicense->sign && Storage::disk('public')->exists($drivingLicense->sign)) {
                Storage::disk('public')->delete($drivingLicense->sign);
            }
            $validated['sign'] = $request->file('sign')->store('licenses/signs', 'public');
        }

        $drivingLicense->update($validated);

        return redirect()->route('user.driving-licenses.index')
            ->with('success', 'License application updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(DrivingLicenseApplication $drivingLicense)
    {
        // Delete associated files
        if ($drivingLicense->photo && Storage::disk('public')->exists($drivingLicense->photo)) {
            Storage::disk('public')->delete($drivingLicense->photo);
        }
        if ($drivingLicense->sign && Storage::disk('public')->exists($drivingLicense->sign)) {
            Storage::disk('public')->delete($drivingLicense->sign);
        }

        $drivingLicense->delete();

        return redirect()->route('user.driving-licenses.index')
            ->with('success', 'License application deleted successfully.');
    }

    /**
     * Common validation rules (for store – photo & sign required)
     */
    private function validationRules(): array
    {
        return [
            'name'             => 'required|string|max:255',
            'dob'              => 'required|date',
            'bloodGroup'       => 'required|string|max:5',
            'fatherOrHusband'  => 'required|string|max:255',
            'address'          => 'required|string',
            'licenceNo'        => 'required|string|max:50',
            'authority'        => 'required|string|max:255',
            'issuDate'         => 'required|date',
            'firstIssuDate'    => 'required|date',
            'validityDate'     => 'required|date',
            'refNo'            => 'required|string|max:100',
            'drivingClass'     => 'required|string',
            // Default for store – must be overridden in update
            'photo'            => 'required|image|mimes:jpeg,png,jpg|max:2048',
            'sign'             => 'required|image|mimes:jpeg,png,jpg|max:2048',
        ];
    }

    /**
     * Custom validation error messages
     */
    private function validationMessages(): array
    {
        return [
            'photo.required' => 'Please upload a photo.',
            'sign.required'  => 'Please upload a signature.',
        ];
    }
}