-- Trade License Management System Database
-- This uses the same `trade_license_applications` table from the main Laravel app

CREATE TABLE IF NOT EXISTS `trade_license_applications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `city` enum('dncc','dscc') NOT NULL,
  `license_no` varchar(255) NOT NULL,
  `business_name` varchar(255) NOT NULL,
  `owner_name` varchar(255) NOT NULL,
  `father_husband_name` varchar(255) NOT NULL,
  `mother_name` varchar(255) NOT NULL,
  `business_nature` varchar(255) NOT NULL,
  `business_type` varchar(255) NOT NULL,
  `business_address_house` varchar(255) DEFAULT NULL,
  `business_address_road` varchar(255) DEFAULT NULL,
  `business_address_block` varchar(255) DEFAULT NULL,
  `business_address_ward` varchar(255) DEFAULT NULL,
  `business_address_thana` varchar(255) DEFAULT NULL,
  `business_address_district` varchar(255) DEFAULT NULL,
  `business_address_postcode` varchar(255) DEFAULT NULL,
  `business_zone` varchar(255) DEFAULT NULL,
  `business_ward_market` varchar(255) DEFAULT NULL,
  `business_address_area` varchar(255) DEFAULT NULL,
  `nid_passport_birth_no` varchar(255) NOT NULL,
  `bin_no` varchar(255) DEFAULT NULL,
  `phone` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `financial_year` varchar(255) NOT NULL,
  `business_start_date` date NOT NULL,
  `current_address_holding` varchar(255) DEFAULT NULL,
  `current_address_road` varchar(255) DEFAULT NULL,
  `current_address_village` varchar(255) DEFAULT NULL,
  `current_address_thana` varchar(255) DEFAULT NULL,
  `current_address_district` varchar(255) DEFAULT NULL,
  `current_address_division` varchar(255) DEFAULT NULL,
  `current_address_postcode` varchar(255) DEFAULT NULL,
  `same_as_current_address` tinyint(1) NOT NULL DEFAULT '0',
  `permanent_address_holding` varchar(255) DEFAULT NULL,
  `permanent_address_road` varchar(255) DEFAULT NULL,
  `permanent_address_village` varchar(255) DEFAULT NULL,
  `permanent_address_thana` varchar(255) DEFAULT NULL,
  `permanent_address_district` varchar(255) DEFAULT NULL,
  `permanent_address_division` varchar(255) DEFAULT NULL,
  `permanent_address_postcode` varchar(255) DEFAULT NULL,
  `license_fee` decimal(12,2) NOT NULL DEFAULT '0.00',
  `surcharge` decimal(12,2) NOT NULL DEFAULT '0.00',
  `tax` decimal(12,2) NOT NULL DEFAULT '0.00',
  `due_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `amendment_fee` decimal(12,2) NOT NULL DEFAULT '0.00',
  `signboard_fee` decimal(12,2) NOT NULL DEFAULT '0.00',
  `vat` decimal(12,2) NOT NULL DEFAULT '0.00',
  `book_price` decimal(12,2) NOT NULL DEFAULT '0.00',
  `form_fee` decimal(12,2) NOT NULL DEFAULT '0.00',
  `other_fee` decimal(12,2) NOT NULL DEFAULT '0.00',
  `total_fee` decimal(12,2) NOT NULL DEFAULT '0.00',
  `license_validity_date` date NOT NULL,
  `owner_photo` varchar(255) DEFAULT NULL,
  `other_documents` text,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `trade_license_applications_user_id_foreign` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
