<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Two-Factor Authentication Setup</title>
</head>
<body>
    <h1>Two-Factor Authentication Setup</h1>
    <p>Scan the QR code below with your authenticator app (e.g., Google Authenticator, Authy, etc.)</p>
    <img src="{{ $QRImage }}" alt="QR Code">
    <p>Or enter this secret key: <strong>{{ $secret }}</strong></p>
    <p>Once you have scanned the QR code, please enter the verification code generated by your authenticator app.</p>
    <form action="{{ route('admin.verify2fa') }}" method="POST">
        @csrf
        <input type="text" name="one_time_password" placeholder="Enter the verification code" required>
        <button type="submit">Verify</button>
    </form>
</body>
</html>
